### ISSUE TITLE
Not sure how to run examples

### ISSUE THREAD

**Issue by 1wheel** [substack/mixmap#1]
I've tried installing the required packages and running `budo choo.js --open`: 

`Error: Cannot find module './manifest.json' from '/Users/207342/Desktop/mixmap/example'`

Is `manifest.json` something that comes from Natural Earth?

thanks!

**Comment by ghost** [comment]
I generated that file and a bunch of tiles from 10m-NE2 raster imagery using gdal_translate. I will have a more complete example later when I have some unmetered internet to upload the data someplace.

**Comment by ghost** [comment]
The example section is now much more comprehensive and I made sure that the dependent files are well seeded. Check out: https://github.com/substack/mixmap/#example

**Comment by 1wheel** [comment]
awesome, thanks again!
