### ISSUE TITLE
Not working by default on Firefox < 55

### ISSUE THREAD

**Issue by ThomasG77** [substack/mixmap#2]
More a comment than an issue to fix as it will become irrelevant in some months.

By default, on Firefox < 55, the demo https://substack.neocities.org/mixmap/demos/ne2swr-cities.html is not working due to "missing" `window.requestIdleCallback` in the console.

Users need to enable it by typing `about:config` in the url bar and then set the key `dom.requestIdleCallback.enabled` to true.

At least, other early users will know. Feel free to close.

**Comment by ghost** [comment]
Thanks for the report. I added a shim, published the update in 1.0.5 and updated all the demos.
